layout_spectrum: 0.5430108
color:
  saturation: 0.7527452
  lightness: 0.121388
  brandStrength: 0.1794174
  rhythmicContrast: 0.7401664
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.1777372
name: JSHorwitz
